version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gym_tracker_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2001
      POSTGRES_DB: gym_tracker
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
